#!/bin/zsh
source ~/.zsh_secrets
version="v0.1.`git rev-list --count HEAD`"
owner=arctair
repository=anniform

jq -n \
  --arg version "$version" \
  --arg description "$description" \
  '{tag_name:$version,target_commitish:"main",name:$version,draft:false,prerelease:false,generate_release_notes:false}' | \
  curl -X POST \
    -H "Accept: application/vnd.github+json" \
    -H "Authorization: token $GITHUB_TOKEN" \
    https://api.github.com/repos/$owner/$repository/releases \
    -d @-
